---
# tasks file for python3
- name: Install python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"