#!/bin/bash

export SENZING_DELAY_IN_SECONDS=60
export SENZING_KAFKA_BOOTSTRAP_SERVER=127.0.0.1:9092
export SENZING_KAFKA_TOPIC=senzing-kafka-topic
export SENZING_INPUT_URL="https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
export SENZING_RECORD_MAX=5000
export SENZING_RECORD_MONITOR=1000
export SENZING_SUBCOMMAND=url-to-kafka