---
# tasks file for postgres-11
- name: Add Apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install YUM repo
  yum:
    name: yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_lsb.major_release|int }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux") and ansible_lsb.major_release|int <= 7

- name: Add Postgres 11 DEB Repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install Postgres 11 Server
  apt:
    name:  ["postgresql-11"]
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install Postgres 11 Server
  yum:
    name: ["postgresql11", "postgresql11-server"]
    state: present
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux") and ansible_lsb.major_release|int <= 7